# Generated by Django 6.0.5 on 2026-05-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('transport_type', models.CharField(choices=[('TRUCK', 'Truck'), ('VAN', 'Van'), ('MOTORCYCLE', 'Motorcycle'), ('CARGO_BIKE', 'Cargo Bike')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity_m3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transport',
                'ordering': ['-created_at'],
            },
        ),
    ]
